// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_plane.proto

// Protobuf Java Version: 3.25.5
package subserver.dataplane.v1;

public final class DataPlaneOuterClass {
  private DataPlaneOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subserver_dataplane_v1_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subserver_dataplane_v1_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subserver_dataplane_v1_DataEnvelope_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subserver_dataplane_v1_DataEnvelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020data_plane.proto\022\026subserver.dataplane." +
      "v1\"\"\n\020SubscribeRequest\022\016\n\006iot_id\030\001 \001(\003\"W" +
      "\n\014DataEnvelope\022\026\n\016correlation_id\030\001 \001(\t\022\016" +
      "\n\006iot_id\030\002 \001(\003\022\021\n\tdata_type\030\003 \001(\t\022\014\n\004dat" +
      "a\030\004 \001(\t2j\n\tDataPlane\022]\n\tSubscribe\022(.subs" +
      "erver.dataplane.v1.SubscribeRequest\032$.su" +
      "bserver.dataplane.v1.DataEnvelope0\001B\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_subserver_dataplane_v1_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_subserver_dataplane_v1_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subserver_dataplane_v1_SubscribeRequest_descriptor,
        new java.lang.String[] { "IotId", });
    internal_static_subserver_dataplane_v1_DataEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_subserver_dataplane_v1_DataEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subserver_dataplane_v1_DataEnvelope_descriptor,
        new java.lang.String[] { "CorrelationId", "IotId", "DataType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
