// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_plane.proto

// Protobuf Java Version: 3.25.5
package subserver.dataplane.v1;

public interface DataEnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subserver.dataplane.v1.DataEnvelope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string correlation_id = 1;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlation_id = 1;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>int64 iot_id = 2;</code>
   * @return The iotId.
   */
  long getIotId();

  /**
   * <code>string data_type = 3;</code>
   * @return The dataType.
   */
  java.lang.String getDataType();
  /**
   * <code>string data_type = 3;</code>
   * @return The bytes for dataType.
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
