// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_plane.proto

// Protobuf Java Version: 3.25.5
package subserver.dataplane.v1;

public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subserver.dataplane.v1.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 iot_id = 1;</code>
   * @return The iotId.
   */
  long getIotId();
}
